services:
  db:
    image: postgres:15-alpine
    container_name: erp_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=erp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: erp_backend
    build:
      context: ./erp-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/erp
    volumes:
      - ./erp-backend:/app
    depends_on:
      - db

  frontend:
    container_name: erp_frontend
    build:
      context: ./erp-frontend
      args:
        - VITE_API_BASE_URL=http://localhost:8000/api/v1
    ports:
      - "3000:3000" # puerto del servidor de desarrollo de Vite
    environment:
      - CHOKIDAR_USEPOLLING=true # hot-reload dentro de Docker
    volumes:
      - ./erp-frontend:/app
      - /app/node_modules # evita que node_modules local sobreescriba el del contenedor
    command: ["npm", "start"]

volumes:
  postgres_data:
